version: '3.8'

services:
  main:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    environment:
      - APP_ENV=local
    depends_on:
      - db
  db:
    image: amazon/dynamodb-local
    restart: always
    ports:
      - 8000:8000
  admin:
    build:
      context: .
      dockerfile: admin.Dockerfile
    ports:
      - 8001:8001
    environment:
      - DYNAMO_ENDPOINT=http://db:8000
      - AWS_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=example
      - AWS_SECRET_ACCESS_KEY=example
    depends_on:
      - db
